services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./pyproject.toml:/app/pyproject.toml
      - uploads:/app/uploads
      - debug:/app/debug
    environment:
      - UPLOAD_DIR=/app/uploads
      - DEBUG_DIR=/app/debug
      - MAX_FILE_SIZE=104857600
      - CHUNK_SIZE=1048576
      - CORS_ORIGINS=http://localhost:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./pyproject.toml:/app/pyproject.toml
      - uploads:/app/uploads
      - debug:/app/debug
      - ./requirements.txt:/app/requirements.txt
    environment:
      - UPLOAD_DIR=/app/uploads
      - DEBUG_DIR=/app/debug
      - MAX_FILE_SIZE=104857600
      - CHUNK_SIZE=1048576
      - CORS_ORIGINS=http://localhost:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  uploads:
  debug:
